### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by S0nicisawesome** [TheLordScruffy/vwii-compat-installer#4]
Can you write a tutorial on how to install this? And does this require an SD card?

**Comment by mkwcat** [comment]
it doesn't require an SD Card or CFW or anything, just launch it through the homebrew launcher and press A

**Comment by S0nicisawesome** [comment]
Is there a way to install it without the homebrew launcher?

**Comment by mkwcat** [comment]
no there's not, but running the homebrew launcher is very easy to do
